#version: '3.1'
#
#services:
#
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"


version: '3.1'

networks:
  dev_network:

services:
  redis:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    networks:
      dev_network:
        aliases:
          - db-redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile_celery
    env_file:
      - ./.env.test
    entrypoint: celery -A celery_app.celery_app worker
    depends_on:
      - redis
    networks:
      dev_network:
    volumes:
      - ./:/app

  app:
    build:
      context: .
    env_file:
      - ./.env.test
    entrypoint: python main.py
    depends_on:
      - redis
    networks:
      dev_network:
    volumes:
      - ./:/app



